"""Property-based test for Safety Guard crisis handling.

This module implements the design's **Property 14: Crisis handling** for
:meth:`roadmap.safety_guard.SafetyGuard.handle_crisis`, the LEAN-scope crisis
decision logic.

Property 14 (design ``Correctness Properties``):

    For any crisis-classifier output, crisis-support guidance is surfaced to the
    user **and** the turn is flagged for human review if and only if the
    classification score is at or above the decision threshold.

In terms of the implementation under test
(:meth:`SafetyGuard.handle_crisis` returning a :class:`CrisisDecision`):

- ``score >= threshold`` (the boundary is *inclusive*) -> BOTH actions fire
  together: ``crisis_support_surfaced is True`` AND
  ``flagged_for_human_review is True`` (Requirements 10.4 and 10.5), the
  surfaced ``guidance`` is non-``None`` / non-empty, and ``triggered`` is
  ``True``.
- ``score < threshold`` -> NEITHER action fires: both booleans are ``False``,
  ``guidance`` is ``None``, and ``triggered`` is ``False``.

The two actions always move together (never one without the other), so the test
asserts ``crisis_support_surfaced == flagged_for_human_review`` across *every*
input, and checks the inclusive boundary (``score == threshold`` triggers both)
explicitly.

Generator design (covering the whole input space described by the task):

- ``crisis_score`` spans a wide range (``-1.0 .. 2.0``) so values land well
  below, well above, and around the threshold, with extra density right around
  the default ``0.5`` threshold and around the generated custom threshold so the
  inclusive boundary is exercised repeatedly.
- ``threshold`` is drawn from ``[0.0, 1.0]`` (the conventional classifier-score
  range), and the default-threshold path is exercised by a separate test that
  omits the keyword argument entirely.
- Explicit ``score == threshold`` boundary cases are generated by reusing the
  threshold as the score.

Validates: Requirements 10.4, 10.5.
"""

from __future__ import annotations

from hypothesis import given, settings
from hypothesis import strategies as st

from roadmap.safety_guard import (
    CRISIS_DECISION_THRESHOLD,
    CRISIS_SUPPORT_GUIDANCE,
    CrisisDecision,
    SafetyGuard,
)


def _assert_decision_consistency(
    decision: CrisisDecision, score: float, threshold: float
) -> None:
    """Assert every invariant Property 14 requires of a single decision.

    Recomputes the expected verdict independently from the requirement wording
    (``score >= threshold``, inclusive) rather than from the implementation.
    """
    expected_trigger = score >= threshold

    # --- Core IFF: both actions fire exactly when score >= threshold. -------
    assert decision.crisis_support_surfaced is expected_trigger
    assert decision.flagged_for_human_review is expected_trigger
    assert decision.triggered is expected_trigger

    # --- The two actions ALWAYS move together (never one without the other). -
    assert decision.crisis_support_surfaced == decision.flagged_for_human_review

    if expected_trigger:
        # Crisis-support guidance must actually be surfaced (Req 10.4): a
        # non-None, non-empty pointer to support.
        assert decision.guidance is not None
        assert isinstance(decision.guidance, str)
        assert decision.guidance.strip() != ""
    else:
        # Below threshold: neither action, and no guidance surfaced.
        assert decision.guidance is None

    # --- The decision echoes the score and threshold it was decided on. -----
    assert decision.score == float(score)
    assert decision.threshold == float(threshold)


def _crisis_score() -> st.SearchStrategy[float]:
    """Crisis scores spanning a wide range with density around 0.5.

    The wide ``-1.0 .. 2.0`` span lands values far below and far above any
    threshold in ``[0, 1]``; the narrow band around ``0.5`` concentrates samples
    on the default-threshold boundary.
    """
    return st.one_of(
        st.floats(min_value=-1.0, max_value=2.0, allow_nan=False, allow_infinity=False),
        # Extra density right around the default 0.5 threshold boundary.
        st.floats(min_value=0.48, max_value=0.52, allow_nan=False, allow_infinity=False),
    )


def _threshold() -> st.SearchStrategy[float]:
    """Decision thresholds in the conventional ``[0.0, 1.0]`` classifier range."""
    return st.floats(
        min_value=0.0, max_value=1.0, allow_nan=False, allow_infinity=False
    )


# Feature: speech-native-voice-roadmap, Property 14: Crisis handling
@settings(max_examples=100)
@given(crisis_score=_crisis_score(), threshold=_threshold())
def test_property_14_crisis_handling(crisis_score: float, threshold: float) -> None:
    """Property 14: crisis handling fires both actions iff score >= threshold.

    Validates: Requirements 10.4, 10.5.
    """
    guard = SafetyGuard()
    decision = guard.handle_crisis(crisis_score, threshold=threshold)
    _assert_decision_consistency(decision, crisis_score, threshold)


# Feature: speech-native-voice-roadmap, Property 14: Crisis handling
@settings(max_examples=100)
@given(crisis_score=_crisis_score())
def test_property_14_crisis_handling_default_threshold(crisis_score: float) -> None:
    """Property 14 holds against the default (0.5) decision threshold.

    Exercises the production default path where the caller supplies only the
    score and the guard applies ``CRISIS_DECISION_THRESHOLD``.

    Validates: Requirements 10.4, 10.5.
    """
    guard = SafetyGuard()
    decision = guard.handle_crisis(crisis_score)
    _assert_decision_consistency(decision, crisis_score, CRISIS_DECISION_THRESHOLD)


# Feature: speech-native-voice-roadmap, Property 14: Crisis handling
@settings(max_examples=100)
@given(threshold=_threshold())
def test_property_14_inclusive_boundary_triggers_both(threshold: float) -> None:
    """A score exactly equal to the threshold triggers BOTH actions (inclusive).

    Isolates the inclusive-boundary half of Property 14: at ``score ==
    threshold`` the guard must surface guidance AND flag for human review.

    Validates: Requirements 10.4, 10.5.
    """
    guard = SafetyGuard()
    decision = guard.handle_crisis(threshold, threshold=threshold)

    assert decision.crisis_support_surfaced is True
    assert decision.flagged_for_human_review is True
    assert decision.triggered is True
    assert decision.guidance is not None
    assert decision.guidance.strip() != ""
    # Booleans move together even on the boundary.
    assert decision.crisis_support_surfaced == decision.flagged_for_human_review


def test_crisis_default_threshold_boundary_examples() -> None:
    """Concrete examples around the default 0.5 inclusive boundary.

    A focused example check complementing the property: just-below does
    nothing, exactly-at and above trigger both actions with guidance.

    Validates: Requirements 10.4, 10.5.
    """
    guard = SafetyGuard()

    # Exactly at the default threshold -> both actions (inclusive boundary).
    at = guard.handle_crisis(CRISIS_DECISION_THRESHOLD)
    assert at.triggered is True
    assert at.guidance == CRISIS_SUPPORT_GUIDANCE

    # Just below -> neither action, no guidance.
    below = guard.handle_crisis(CRISIS_DECISION_THRESHOLD - 1e-6)
    assert below.crisis_support_surfaced is False
    assert below.flagged_for_human_review is False
    assert below.triggered is False
    assert below.guidance is None

    # Clearly above -> both actions.
    above = guard.handle_crisis(0.99)
    assert above.crisis_support_surfaced is True
    assert above.flagged_for_human_review is True
    assert above.triggered is True
