/**
 * SoulYatri Client — Audio Session Orchestrator (Phase 2)
 * =======================================================
 * Ties the three Phase-2 pieces into one bidirectional audio loop:
 *
 *   MicrophoneCapture (2A) → RealtimeTransportClient (2B) → gateway
 *   gateway → RealtimeTransportClient (2B) → StreamPlayer (2C)
 *
 * This is the concrete realization of the `final_use.md` §2 skeleton:
 *
 * ```ts
 * export interface AudioFrame { pcm: Float32Array; tsMs: number }
 * export interface AudioSession {
 *   start(): Promise<void>
 *   stop(): Promise<void>
 *   send(frame: AudioFrame): void
 * }
 * ```
 *
 * Acceptance (final_use.md §7.1 client contract):
 * - mic capture works across supported devices (delegated to {@link MicrophoneCapture})
 * - reconnects are transparent when possible (delegated to {@link RealtimeTransportClient})
 * - playback stops cleanly on interruption (delegated to {@link StreamPlayer})
 * - client telemetry includes send/receive jitter and buffer depth (see {@link SessionTelemetry})
 *
 * Design
 * ------
 * Collaborators are injected behind narrow interfaces ({@link CaptureLike},
 * {@link TransportLike}, {@link PlayerLike}) so the session is unit-testable with
 * fakes and never requires WebAudio in tests. In the browser, the defaults build
 * real {@link MicrophoneCapture} / {@link RealtimeTransportClient} / {@link StreamPlayer}
 * instances and wire the capture frame-sink straight into {@link send}.
 */

import { AudioFrame } from "./types";
import {
  CaptureLogger,
  consoleLogger,
  MicrophoneCapture,
  CaptureOptions,
} from "./capture";
import {
  RealtimeTransportClient,
  TransportClientOptions,
  TransportState,
} from "./webrtc";
import { StreamPlayer, StreamPlayerOptions } from "../playback/stream_player";

/**
 * The minimal session contract from the guide skeleton (final_use.md §2).
 * `send` is the hook the capture path calls for every produced frame.
 */
export interface AudioSession {
  start(): Promise<void>;
  stop(): Promise<void>;
  send(frame: AudioFrame): void;
}

/** Narrow view of a capture engine the session drives. */
export interface CaptureLike {
  start(): Promise<void>;
  stop(): Promise<void>;
  readonly isRunning: boolean;
  readonly sampleRate: number;
}

/** Narrow view of the realtime transport the session drives. */
export interface TransportLike {
  connect(): Promise<void>;
  close(): void;
  send(frame: AudioFrame): void;
  end(): void;
  readonly isConnected: boolean;
  /** Optional inbound-frame sink the session assigns when injected. */
  onInbound?: (frame: AudioFrame) => void;
  /** Optional control-message sink the session assigns when injected. */
  onControl?: (msg: Record<string, unknown>) => void;
}

/** Narrow view of the playback engine the session drives. */
export interface PlayerLike {
  beginTurn(): void;
  enqueue(chunk: { pcm: Float32Array; sampleRate: number; seq?: number; isFinal?: boolean }): void;
  fadeOut(): Promise<void>;
  hardStop(): void;
}

/** Lightweight per-session telemetry (final_use.md §7.1: jitter + buffer depth). */
export interface SessionTelemetry {
  framesSent: number;
  framesReceived: number;
  /** Estimated inter-arrival jitter of inbound frames (ms, smoothed). */
  receiveJitterMs: number;
  /** Estimated inter-emit jitter of outbound frames (ms, smoothed). */
  sendJitterMs: number;
  /** Frames currently buffered awaiting (re)connect, surfaced by the transport. */
  outboundBufferDepth: number;
  reconnectCount: number;
  state: SessionState;
}

export type SessionState = "idle" | "starting" | "running" | "stopping" | "stopped" | "error";

export interface AudioSessionOptions {
  /** Capture/playback sample-rate alignment (Hz). Uplink default 16000. */
  sampleRate?: number;
  /** Playback (downlink) sample rate from the gateway. Default 24000. */
  playbackSampleRate?: number;
  /** Gateway base URL, e.g. ws://localhost:8000/ws/audio. */
  serverUrl?: string;
  /** Session id; auto-generated by the transport if omitted. */
  sessionId?: string;
  /** Preferred input device id (from MicrophoneCapture.listInputDevices). */
  deviceId?: string;
  /** Language hint forwarded as session metadata. */
  language?: string;
  /** Extra capture options (AEC/NS/AGC toggles, frame size). */
  captureOptions?: Partial<CaptureOptions>;
  /** Extra transport options. */
  transportOptions?: Partial<TransportClientOptions>;
  /** Extra player options (fade duration, jitter window). */
  playerOptions?: Partial<StreamPlayerOptions>;
  /** Notified on session-state changes (for UI). */
  onState?: (state: SessionState) => void;
  /** Notified on control messages from the gateway (transcripts, turn meta…). */
  onControl?: (msg: Record<string, unknown>) => void;
  logger?: CaptureLogger;

  // --- Injection points (tests / alternative implementations) ---
  capture?: CaptureLike;
  transport?: TransportLike;
  player?: PlayerLike;
}

/**
 * Concrete {@link AudioSession}. Owns the capture → transport → playback wiring,
 * surfaces telemetry, and exposes {@link bargeIn} so the UI / barge-in detector
 * can stop assistant audio cleanly the instant the user speaks over it.
 */
export class SoulYatriAudioSession implements AudioSession {
  private readonly logger: CaptureLogger;
  private readonly playbackSampleRate: number;
  private readonly onStateCb?: (state: SessionState) => void;
  private readonly onControlCb?: (msg: Record<string, unknown>) => void;

  private capture: CaptureLike;
  private transport: TransportLike;
  private player: PlayerLike;
  /** Set only when the transport is the built-in client (exposes metadata). */
  private readonly rtcClient: RealtimeTransportClient | null;

  private state: SessionState = "idle";
  private framesSent = 0;
  private framesReceived = 0;
  private lastSendTs = 0;
  private lastReceiveTs = 0;
  private sendJitterMs = 0;
  private receiveJitterMs = 0;
  private reconnectCount = 0;
  private playing = false;

  constructor(options: AudioSessionOptions = {}) {
    this.logger = options.logger ?? consoleLogger;
    const sampleRate = options.sampleRate ?? 16000;
    this.playbackSampleRate = options.playbackSampleRate ?? 24000;
    this.onStateCb = options.onState;
    this.onControlCb = options.onControl;

    // Player: injected or a real StreamPlayer.
    this.player =
      options.player ??
      new StreamPlayer({
        logger: this.logger,
        onStart: () => {
          this.playing = true;
        },
        onEnd: () => {
          this.playing = false;
        },
        ...options.playerOptions,
      });

    // Transport: injected or a real RealtimeTransportClient wired to the player.
    if (options.transport) {
      this.transport = options.transport;
      this.rtcClient = null;
      // Injected transports deliver inbound audio / control via these sinks.
      this.transport.onInbound = (frame) => this.handleInbound(frame);
      this.transport.onControl = (msg) => this.handleControl(msg);
    } else {
      const client = new RealtimeTransportClient({
        sessionId: options.sessionId,
        sampleRate,
        serverUrl: options.serverUrl,
        language: options.language,
        logger: this.logger,
        onState: (s) => this.handleTransportState(s),
        onInbound: (frame) => this.handleInbound(frame),
        onControl: (msg) => this.handleControl(msg),
        ...options.transportOptions,
      });
      this.transport = client;
      this.rtcClient = client;
    }

    // Capture: injected or a real MicrophoneCapture whose frames feed `send`.
    this.capture =
      options.capture ??
      new MicrophoneCapture({
        targetSampleRate: sampleRate,
        deviceId: options.deviceId,
        logger: this.logger,
        onFrame: (frame) => this.send(frame),
        ...options.captureOptions,
      });
  }

  get currentState(): SessionState {
    return this.state;
  }

  get isRunning(): boolean {
    return this.state === "running";
  }

  /** Connect transport then start capturing. Idempotent while running. */
  async start(): Promise<void> {
    if (this.state === "running" || this.state === "starting") {
      this.logger.warn("session_start_ignored", { state: this.state });
      return;
    }
    this.setState("starting");
    try {
      await this.transport.connect();
      await this.capture.start();
      this.setState("running");
      this.logger.info("session_started", {
        sampleRate: this.capture.sampleRate,
        playbackSampleRate: this.playbackSampleRate,
      });
    } catch (err) {
      this.setState("error");
      this.logger.error("session_start_failed", { error: String(err) });
      // Best-effort cleanup so a failed start doesn't leak the mic/socket.
      await this.safeStopCapture();
      throw err;
    }
  }

  /** Stop capture, signal end-of-session, and tear down playback. */
  async stop(): Promise<void> {
    if (this.state === "stopped" || this.state === "stopping") return;
    this.setState("stopping");
    await this.safeStopCapture();
    try {
      this.transport.end();
    } catch {
      /* transport may already be closed */
    }
    this.transport.close();
    this.player.hardStop();
    this.setState("stopped");
    this.logger.info("session_stopped", {
      framesSent: this.framesSent,
      framesReceived: this.framesReceived,
    });
  }

  /**
   * Forward a captured frame to the transport. Called by the capture engine for
   * every produced frame; also callable directly (e.g. for synthetic input).
   */
  send(frame: AudioFrame): void {
    const now = frame.tsMs || Date.now();
    if (this.lastSendTs) {
      this.sendJitterMs = this.smooth(this.sendJitterMs, Math.abs(now - this.lastSendTs));
    }
    this.lastSendTs = now;
    this.framesSent += 1;
    this.transport.send(frame);
  }

  /**
   * Barge-in: stop assistant playback immediately. `hard` cuts instantly (lowest
   * latency, may click), `fade` ramps out cleanly. Default hard for barge-in.
   */
  async bargeIn(mode: "hard" | "fade" = "hard"): Promise<void> {
    if (!this.playing) {
      this.logger.info("barge_in_noop_not_playing");
      return;
    }
    this.logger.info("barge_in", { mode });
    if (mode === "fade") {
      await this.player.fadeOut();
    } else {
      this.player.hardStop();
    }
    this.playing = false;
  }

  /** Begin a new assistant playback turn (resets fade/jitter cursors). */
  beginPlaybackTurn(): void {
    this.player.beginTurn();
  }

  /** Snapshot of send/receive jitter, buffer depth, and counters. */
  telemetry(): SessionTelemetry {
    return {
      framesSent: this.framesSent,
      framesReceived: this.framesReceived,
      receiveJitterMs: Math.round(this.receiveJitterMs * 100) / 100,
      sendJitterMs: Math.round(this.sendJitterMs * 100) / 100,
      outboundBufferDepth: this.rtcClient?.metadata.framesBuffered ?? 0,
      reconnectCount: this.rtcClient?.metadata.reconnectCount ?? this.reconnectCount,
      state: this.state,
    };
  }

  // -- internals ----------------------------------------------------------
  private handleInbound(frame: AudioFrame): void {
    const now = frame.tsMs || Date.now();
    if (this.lastReceiveTs) {
      this.receiveJitterMs = this.smooth(this.receiveJitterMs, Math.abs(now - this.lastReceiveTs));
    }
    this.lastReceiveTs = now;
    this.framesReceived += 1;
    this.playing = true;
    this.player.enqueue({
      pcm: frame.pcm,
      sampleRate: frame.sampleRate ?? this.playbackSampleRate,
      seq: frame.seq,
    });
  }

  private handleControl(msg: Record<string, unknown>): void {
    // Server-driven interruption (e.g. user barge-in detected at the edge).
    if (msg.type === "interrupt" || msg.barge_in === true) {
      void this.bargeIn(msg.mode === "fade" ? "fade" : "hard");
    }
    this.onControlCb?.(msg);
  }

  private handleTransportState(s: TransportState): void {
    if (s === "reconnecting") this.reconnectCount += 1;
    this.logger.info("session_transport_state", { transportState: s });
    // The transport recovers itself; the session stays "running" across blips so
    // capture keeps producing frames (which the transport buffers until reconnect).
    if (s === "closed" && this.state === "running") {
      this.setState("stopped");
    }
  }

  private async safeStopCapture(): Promise<void> {
    try {
      if (this.capture.isRunning) await this.capture.stop();
    } catch (err) {
      this.logger.warn("session_capture_stop_failed", { error: String(err) });
    }
  }

  private setState(state: SessionState): void {
    if (this.state === state) return;
    this.state = state;
    this.onStateCb?.(state);
  }

  /** Exponential moving average for jitter smoothing (α = 0.2). */
  private smooth(prev: number, sample: number): number {
    return prev === 0 ? sample : prev * 0.8 + sample * 0.2;
  }
}
