"""
training/data_engine/schema.py — Phase 14A dataset registry & record schema.

Defines the dataset schema for every training data kind the SoulYatri data moat needs:

  * ASR transcripts                 (final_use.md §13.1, Phase 7A)
  * emotion / SER labels            (final_use.md §9A, §13)
  * speaker embeddings / identity   (ECAPA-TDNN, final_use.md §2.2)
  * Hinglish / code-switch pairs    (Romanized ↔ native script, §11.2, §13.2)
  * preference data (DPO-lite)      (chosen/rejected pairs, §11.1, Phase 14B)

**Non-negotiable rule (final_use.md §1.3, §2.4, §13.2):** every dataset record carries
**provenance** + **consent** metadata. Records missing provenance or consent are rejected
by the validators. This makes the consent-first, auditable data discipline structural
rather than convention.

CPU/no-weights rule (DECISIONS.md D-008): pydantic v2 models + stdlib enums only. No torch,
transformers, moshi, or mimi imports. Imports cleanly on a CPU-only machine.

Starter record shape (final_use.md §14 skeleton) is a strict subset of ``DatasetRecord``:

    {"sample_id":"...","lang":"hinglish","romanized":true,"emotion":"warm_ack",
     "source":"synthetic_v1","consent":"n/a","split":"train"}
"""

from __future__ import annotations

import hashlib
import json
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

__all__ = [
    "DataKind",
    "Language",
    "DataSplit",
    "SourceType",
    "ConsentStatus",
    "Provenance",
    "Consent",
    "RecordBase",
    "ASRRecord",
    "EmotionRecord",
    "SpeakerRecord",
    "HinglishPairRecord",
    "PreferenceRecord",
    "DatasetRecord",
    "DatasetManifest",
    "RECORD_MODELS",
    "build_record",
    "validate_record",
    "validate_records",
    "record_hash",
    "ProvenanceError",
    "ConsentError",
]


# ---------------------------------------------------------------------------
# Enums (closed value sets)
# ---------------------------------------------------------------------------
class DataKind(str, Enum):
    """The kind of training datum a record carries."""

    asr = "asr"
    emotion = "emotion"
    speaker = "speaker"
    hinglish_pair = "hinglish_pair"
    preference = "preference"


class Language(str, Enum):
    """Supported languages (final_use.md §1.3: Hindi + English + Hinglish)."""

    en = "en"
    hi = "hi"
    hinglish = "hinglish"


class DataSplit(str, Enum):
    """Train / validation / test split tag."""

    train = "train"
    val = "val"
    test = "test"


class SourceType(str, Enum):
    """Where a record originated (high-level provenance class)."""

    synthetic = "synthetic"  # generated by training/data_engine/synthetic.py
    real_consented = "real_consented"  # consented real user/contributor utterance
    public_open = "public_open"  # open dataset (IndicVoices, Common Voice, …)
    augmented = "augmented"  # derived/augmented from another record


class ConsentStatus(str, Enum):
    """Consent state of a record (final_use.md §2.4 consent-first rule)."""

    granted = "granted"  # explicit consent on file (consent_id required)
    not_applicable = "not_applicable"  # synthetic data with no human subject ("n/a")
    public_license = "public_license"  # covered by an open dataset license
    revoked = "revoked"  # consent withdrawn — must be excluded from training
    pending = "pending"  # collected but not yet confirmed — not training-eligible


# Consent states that make a record eligible to be used for training/adaptation.
TRAINING_ELIGIBLE_CONSENT = frozenset(
    {ConsentStatus.granted, ConsentStatus.not_applicable, ConsentStatus.public_license}
)


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------
class ProvenanceError(ValueError):
    """Raised when a record is missing required provenance metadata."""


class ConsentError(ValueError):
    """Raised when a record is missing required consent metadata."""


# ---------------------------------------------------------------------------
# Provenance + consent value objects
# ---------------------------------------------------------------------------
class Provenance(BaseModel):
    """Where a record came from and how it was produced (audit trail).

    Every dataset record MUST carry provenance. ``source_type`` + ``source_id`` give a
    minimally auditable origin; the optional fields support reproducibility.
    """

    model_config = ConfigDict(extra="forbid")

    source_type: SourceType
    source_id: str = Field(
        min_length=1,
        description="Stable origin id, e.g. 'synthetic_v1', 'commonvoice_hi_17', 'collect_2024_batch3'.",
    )
    pipeline_version: str = Field(
        default="v1", min_length=1, description="Version of the engine/collector that produced it."
    )
    parent_sample_id: str | None = Field(
        default=None, description="For augmented/derived records: the source sample id."
    )
    created_ts: str | None = Field(
        default=None, description="ISO-8601 creation timestamp (optional)."
    )
    notes: str = Field(default="", description="Free-form audit notes.")

    @field_validator("source_id", "pipeline_version")
    @classmethod
    def _not_blank(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("must not be blank")
        return v


class Consent(BaseModel):
    """Consent metadata attached to every record (consent-first, auditable).

    Validation rule: when ``status == granted`` a ``consent_id`` MUST be present (proof of
    consent on file). Synthetic data uses ``not_applicable``; open datasets use
    ``public_license`` with a ``license`` string.
    """

    model_config = ConfigDict(extra="forbid")

    status: ConsentStatus
    consent_id: str | None = Field(
        default=None, description="Reference to the signed consent record (required if granted)."
    )
    license: str | None = Field(
        default=None,
        description="License identifier for public_license data (e.g. 'CC0', 'MPL-2.0').",
    )
    subject_id: str | None = Field(
        default=None, description="Pseudonymous subject id for revocation handling."
    )
    can_train: bool = Field(
        default=True, description="Whether this record may be used for adaptation/training."
    )

    @model_validator(mode="after")
    def _check_consent_consistency(self) -> Consent:
        if self.status == ConsentStatus.granted and not (
            self.consent_id and self.consent_id.strip()
        ):
            raise ConsentError("consent.status='granted' requires a non-empty consent_id")
        if self.status == ConsentStatus.public_license and not (
            self.license and self.license.strip()
        ):
            raise ConsentError("consent.status='public_license' requires a license identifier")
        # Records that are not training-eligible must not be flagged trainable.
        if self.status not in TRAINING_ELIGIBLE_CONSENT and self.can_train:
            object.__setattr__(self, "can_train", False)
        return self

    @property
    def is_training_eligible(self) -> bool:
        return self.can_train and self.status in TRAINING_ELIGIBLE_CONSENT


# ---------------------------------------------------------------------------
# Record base — provenance + consent enforced for every kind
# ---------------------------------------------------------------------------
class RecordBase(BaseModel):
    """Common fields shared by every dataset record kind.

    Enforces the project-wide rule: **no record without provenance + consent**. Pydantic
    makes both fields required (no default), so a missing block fails validation before any
    kind-specific logic runs.
    """

    model_config = ConfigDict(extra="forbid")

    sample_id: str = Field(min_length=1, description="Unique id for this record.")
    kind: DataKind
    lang: Language = Field(default=Language.hinglish)
    split: DataSplit = Field(default=DataSplit.train)
    provenance: Provenance  # required — no default
    consent: Consent  # required — no default
    tags: list[str] = Field(default_factory=list)

    @field_validator("sample_id")
    @classmethod
    def _sample_id_not_blank(cls, v: str) -> str:
        if not v or not v.strip():
            raise ProvenanceError("sample_id must not be blank")
        return v

    @property
    def is_training_eligible(self) -> bool:
        """A record is training-eligible only if its consent allows it."""
        return self.consent.is_training_eligible


# ---------------------------------------------------------------------------
# Kind-specific records
# ---------------------------------------------------------------------------
class ASRRecord(RecordBase):
    """ASR/transcript datum (final_use.md Phase 7A, §13.1)."""

    kind: DataKind = Field(default=DataKind.asr, frozen=True)
    audio_path: str = Field(min_length=1, description="Path/URI to the audio clip.")
    transcript: str = Field(description="Reference transcript.")
    duration_ms: int = Field(ge=0, description="Clip duration in milliseconds.")
    sample_rate: int = Field(default=16000, gt=0)
    romanized: bool = Field(
        default=False, description="True if the transcript is Romanized (Latin script)."
    )

    @field_validator("kind")
    @classmethod
    def _kind_fixed(cls, v: DataKind) -> DataKind:
        if v != DataKind.asr:
            raise ValueError("ASRRecord.kind must be 'asr'")
        return v


class EmotionRecord(RecordBase):
    """Emotion/SER label datum (final_use.md §9A, §13).

    Carries either a discrete ``label`` (e.g. 'warm_ack') or continuous V/A/D scalars
    (compatible with shared.contracts.EmotionState), or both.
    """

    kind: DataKind = Field(default=DataKind.emotion, frozen=True)
    audio_path: str | None = Field(default=None, description="Path/URI to the audio clip.")
    text: str | None = Field(default=None, description="Optional reference text.")
    label: str | None = Field(default=None, description="Discrete emotion label.")
    valence: float | None = Field(default=None, ge=-1.0, le=1.0)
    arousal: float | None = Field(default=None, ge=-1.0, le=1.0)
    dominance: float | None = Field(default=None, ge=-1.0, le=1.0)

    @model_validator(mode="after")
    def _needs_some_label(self) -> EmotionRecord:
        has_continuous = any(v is not None for v in (self.valence, self.arousal, self.dominance))
        if not self.label and not has_continuous:
            raise ValueError("EmotionRecord needs a discrete label or at least one V/A/D scalar")
        return self


class SpeakerRecord(RecordBase):
    """Speaker-identity datum for speaker tracking / style continuity (ECAPA-TDNN)."""

    kind: DataKind = Field(default=DataKind.speaker, frozen=True)
    audio_path: str = Field(min_length=1, description="Path/URI to the audio clip.")
    speaker_id: str = Field(min_length=1, description="Pseudonymous speaker id.")
    duration_ms: int = Field(ge=0)
    embedding_dim: int | None = Field(
        default=None, gt=0, description="ECAPA embedding dim if known."
    )


class HinglishPairRecord(RecordBase):
    """Romanized ↔ native-script code-switch pair (final_use.md §11.2, §13.2, Phase 14C).

    The data moat: transliteration-aware code-switch corpus. ``romanized_text`` is Latin
    script; ``native_text`` is Devanagari; ``intent``/``emotion`` describe the turn.
    """

    kind: DataKind = Field(default=DataKind.hinglish_pair, frozen=True)
    lang: Language = Field(default=Language.hinglish)
    romanized_text: str = Field(min_length=1, description="Romanized (Latin-script) form.")
    native_text: str = Field(min_length=1, description="Native-script (Devanagari) form.")
    intent: str = Field(default="unknown", description="Turn intent, e.g. 'greeting', 'warm_ack'.")
    emotion: str = Field(default="neutral", description="Emotion tag, e.g. 'warm_ack'.")
    reviewed: bool = Field(default=False, description="Passed human review (Phase 14C).")


class PreferenceRecord(RecordBase):
    """Preference pair for DPO-lite optimization (final_use.md §11.1, Phase 14B).

    ``prompt`` with a ``chosen`` (preferred) and ``rejected`` response. ``margin`` is an
    optional strength-of-preference scalar.
    """

    kind: DataKind = Field(default=DataKind.preference, frozen=True)
    prompt: str = Field(min_length=1)
    chosen: str = Field(min_length=1, description="Preferred response.")
    rejected: str = Field(min_length=1, description="Dispreferred response.")
    margin: float | None = Field(default=None, ge=0.0, le=1.0)

    @model_validator(mode="after")
    def _chosen_differs(self) -> PreferenceRecord:
        if self.chosen.strip() == self.rejected.strip():
            raise ValueError("PreferenceRecord.chosen and .rejected must differ")
        return self


# Map of kind → concrete model, used by build_record / validate_record.
RECORD_MODELS: dict[DataKind, type[RecordBase]] = {
    DataKind.asr: ASRRecord,
    DataKind.emotion: EmotionRecord,
    DataKind.speaker: SpeakerRecord,
    DataKind.hinglish_pair: HinglishPairRecord,
    DataKind.preference: PreferenceRecord,
}

# A convenient union alias for callers/tests.
DatasetRecord = RecordBase


# ---------------------------------------------------------------------------
# Factory + validation helpers
# ---------------------------------------------------------------------------
def _require_provenance_consent(data: dict[str, Any]) -> None:
    """Reject raw dicts missing provenance/consent *before* model coercion.

    Pydantic would also reject these (the fields are required), but raising the domain
    errors here gives clearer, contract-specific messages and guarantees the rule is
    enforced even if a caller bypasses the model.
    """
    if not isinstance(data, dict):
        raise TypeError("record data must be a dict")
    if "provenance" not in data or data.get("provenance") in (None, {}, ""):
        raise ProvenanceError("record is missing required 'provenance' metadata")
    if "consent" not in data or data.get("consent") in (None, {}, ""):
        raise ConsentError("record is missing required 'consent' metadata")


def build_record(data: dict[str, Any]) -> RecordBase:
    """Construct the correct record subclass from a raw dict.

    Enforces provenance + consent presence, then dispatches on ``kind``. Raises
    ``ProvenanceError`` / ``ConsentError`` for missing audit metadata, ``ValueError`` for
    an unknown/missing kind, and ``pydantic.ValidationError`` for field problems.
    """
    _require_provenance_consent(data)
    raw_kind = data.get("kind")
    if raw_kind is None:
        raise ValueError("record is missing required 'kind'")
    try:
        kind = DataKind(raw_kind)
    except ValueError as exc:
        raise ValueError(f"unknown data kind: {raw_kind!r}") from exc
    model = RECORD_MODELS[kind]
    return model.model_validate(data)


def validate_record(data: dict[str, Any]) -> RecordBase:
    """Alias for build_record — validate a single raw record dict."""
    return build_record(data)


def validate_records(items: list[dict[str, Any]]) -> tuple[list[RecordBase], list[dict[str, Any]]]:
    """Validate a batch of raw records.

    Returns ``(valid_records, rejected)`` where each rejected entry is
    ``{"index", "error", "data"}``. Does not raise on individual bad records, so a whole
    dataset can be screened in one pass (useful for dry-run validation).
    """
    valid: list[RecordBase] = []
    rejected: list[dict[str, Any]] = []
    for i, item in enumerate(items):
        try:
            valid.append(build_record(item))
        except Exception as exc:  # collect, don't abort the batch
            rejected.append({"index": i, "error": f"{type(exc).__name__}: {exc}", "data": item})
    return valid, rejected


def record_hash(record: RecordBase | dict[str, Any]) -> str:
    """Deterministic SHA-256 of a record's canonical JSON (for data-hash manifests).

    Used by the SFT/DPO run manifests to record a stable ``data_hash`` without reading raw
    bytes off disk.
    """
    if isinstance(record, RecordBase):
        payload = record.model_dump(mode="json")
    else:
        payload = record
    canonical = json.dumps(payload, sort_keys=True, ensure_ascii=False, default=str)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Dataset manifest (registry-level)
# ---------------------------------------------------------------------------
class DatasetManifest(BaseModel):
    """Top-level descriptor for a registered dataset (the 'registry' in 14A).

    Aggregates counts by kind/split/consent and exposes a single ``dataset_hash`` over its
    member record hashes for reproducibility in run manifests.
    """

    model_config = ConfigDict(extra="forbid")

    dataset_id: str = Field(min_length=1)
    description: str = Field(default="")
    record_count: int = Field(default=0, ge=0)
    counts_by_kind: dict[str, int] = Field(default_factory=dict)
    counts_by_split: dict[str, int] = Field(default_factory=dict)
    counts_by_consent: dict[str, int] = Field(default_factory=dict)
    training_eligible_count: int = Field(default=0, ge=0)
    dataset_hash: str = Field(default="")

    @classmethod
    def from_records(
        cls, dataset_id: str, records: list[RecordBase], description: str = ""
    ) -> DatasetManifest:
        """Build a manifest by summarizing validated records."""
        by_kind: dict[str, int] = {}
        by_split: dict[str, int] = {}
        by_consent: dict[str, int] = {}
        eligible = 0
        hashes: list[str] = []
        for r in records:
            by_kind[r.kind.value] = by_kind.get(r.kind.value, 0) + 1
            by_split[r.split.value] = by_split.get(r.split.value, 0) + 1
            by_consent[r.consent.status.value] = by_consent.get(r.consent.status.value, 0) + 1
            if r.is_training_eligible:
                eligible += 1
            hashes.append(record_hash(r))
        digest = hashlib.sha256("".join(sorted(hashes)).encode("utf-8")).hexdigest()
        return cls(
            dataset_id=dataset_id,
            description=description,
            record_count=len(records),
            counts_by_kind=by_kind,
            counts_by_split=by_split,
            counts_by_consent=by_consent,
            training_eligible_count=eligible,
            dataset_hash=digest,
        )
